#!/bin/sh
# Colorized commands
alias \
    ls="lsd" \
    lst="lsd -Slh --tree" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \

# Package management
alias \
    xbs="sudo xbps-install" \
    xbr="sudo xbps-remove -Rv" \
    xbq="xbps-query -Rs" \

# Safe file operations
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    mkd="mkdir -pv" \
    clear="tput clear" \
    reset="tput reset"

# Use neovim if available
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Usefull alias for my workflow
alias rvv=" cd rvv-examples/ && sudo docker run -ti --mount type=bind,source="$(pwd)"/,target=/home/app/ riscv:riscv-toolchain"
