#!/bin/sh
# Colorized commands
alias \
    ls="lsd" \
    lst="lsd -Slh --tree" \
    dir="dir --color=auto" \
    vdir="vdir --color=auto" \
    grep="grep --color=auto" \
    fgrep="fgrep --color=auto" \
    egrep="egrep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi" \
    dfg="df -BG" \
    dfm="df -BM" \
    ip="ip --color=auto"

# Package management
alias \
    xbs="sudo xbps-install" \
    xbr="sudo xbps-remove -Rv" \
    xbq="xbps-query -Rs" \
    apti="sudo apt-get install --no-install-recommends" \
    aptr="sudo apt-get --purge autoremove" \
    zyi="sudo zypper install --no-recommends" \
    zyr="sudo zypper remove --clean-deps --no-confirm" \
    flinst="flatpak install" \
    flrem="flatpak uninstall --delete-data" \
    flclean="flatpak uninstall --unused --delete-data -y && flatpak repair"

# Safe file operations
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    mkd="mkdir -pv" \
    clear="tput clear" \
    reset="tput reset"

# Version control
alias gcl='git clone --depth 1'

# Use neovim if available
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# XDG-compliant tmux configuration
alias tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"
